### ISSUE TITLE
Issue with Safari Version 12.0 (12606.2.11) on Mac

### ISSUE THREAD

**Issue by pawankumar01** [bersLucas/FollowCursor#6]
The library is working fine with Chrome. When I use same to test in Safari, it is repainting the image with white color and it rotates white color randomly instead of showing the actual image. Attaching the images for reference. It appears something like below:-

<img width="359" alt="screen shot 2018-11-22 at 21 27 34" src="https://user-images.githubusercontent.com/8166061/48913471-76ca1a00-ee9e-11e8-9bfb-83060e7519eb.png">
<img width="1131" alt="screen shot 2018-11-22 at 21 27 08" src="https://user-images.githubusercontent.com/8166061/48913472-76ca1a00-ee9e-11e8-9473-d70b43ebbb80.png">

**Comment by bersLucas** [comment]
Can you send me a codepen or a working demo of your implementation? I'm using Safari 12.0 and I can't replicate
